#include "HSTokenType.h"

const std::string HS_TOKENTYPE_NAMES[] = {"TOK_ID", "TOK_INT", "TOK_FLOAT", "TOK_STRING",
"TOK_PLUS", "TOK_MINUS", "TOK_STAR", "TOK_SLASH", "TOK_PERCENT", "TOK_ASSIGN",
"TOK_LPAREN", "TOK_RPAREN", "TOK_LESS", "TOK_GRE", "TOK_COMMA", "TOK_DOT",
"TOK_EQ", "TOK_LSEQ", "TOK_GREQ", "TOK_NEQ",
"TOK_IF", "TOK_ELIF", "TOK_ELSE", "TOK_PRINT", "TOK_WHILE", "TOK_BREAK", "TOK_CONTINUE", "TOK_DO", "TOK_OD", "TOK_AND", "TOK_OR", "TOK_NOT",
"TOK_EOL", "TOK_EOF",
"TOK_TRUE", "TOK_FALSE", "TOK_NULL"};
